export const PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEPENDENCIES = "dependencies"
export const PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEV_DEPENDENCIES = "devDependencies"
export const PACKAGE_MANIFEST_DEPENDENCY_FIELD__PEER_DEPENDENCIES = "peerDependencies"
export const PACKAGE_MANIFEST_DEPENDENCY_FIELD__OPTIONAL_DEPENDENCIES = "optionalDependencies"

export const PACKAGE_MANIFEST_DEPENDENCY_FIELDS = [
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEPENDENCIES,
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEV_DEPENDENCIES,
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__PEER_DEPENDENCIES,
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__OPTIONAL_DEPENDENCIES,
] as const

export const PACKAGE_MANIFEST_INSTALL_TARGET_FIELDS = [
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEPENDENCIES,
  PACKAGE_MANIFEST_DEPENDENCY_FIELD__DEV_DEPENDENCIES,
] as const

export type TPackageManifestDependencyField = (typeof PACKAGE_MANIFEST_DEPENDENCY_FIELDS)[number]
export type TPackageManifestInstallTargetField = (typeof PACKAGE_MANIFEST_INSTALL_TARGET_FIELDS)[number]
