export const LOCAL_REGISTRY_SOURCE_SCHEMA_VERSION = 1
export const REGISTRY_INSTALL_PLAN_SCHEMA_VERSION = 1

export const INSTALL_PLAN_FILE_STATUS__MISSING = "missing"
export const INSTALL_PLAN_FILE_STATUS__EXISTING = "existing"

export const INSTALL_PLAN_FILE_STATUSES = [
  INSTALL_PLAN_FILE_STATUS__MISSING,
  INSTALL_PLAN_FILE_STATUS__EXISTING,
] as const

export const INSTALL_PLAN_TARGET_RESOLUTION__WRITE = "write"
export const INSTALL_PLAN_TARGET_RESOLUTION__REUSE_EXISTING = "reuse-existing"
export const INSTALL_PLAN_TARGET_RESOLUTION__BLOCK_EXISTING = "block-existing"

export const INSTALL_PLAN_TARGET_RESOLUTIONS = [
  INSTALL_PLAN_TARGET_RESOLUTION__WRITE,
  INSTALL_PLAN_TARGET_RESOLUTION__REUSE_EXISTING,
  INSTALL_PLAN_TARGET_RESOLUTION__BLOCK_EXISTING,
] as const

export const INSTALL_PLAN_TARGET_COMPATIBILITY__CONTENT_HASH_MATCH = "content-hash-match"
export const INSTALL_PLAN_TARGET_COMPATIBILITY__TYPESCRIPT_EXPORT_SUPERSET = "typescript-export-superset"

export const INSTALL_PLAN_TARGET_COMPATIBILITIES = [
  INSTALL_PLAN_TARGET_COMPATIBILITY__CONTENT_HASH_MATCH,
  INSTALL_PLAN_TARGET_COMPATIBILITY__TYPESCRIPT_EXPORT_SUPERSET,
] as const

export const INSTALL_PLAN_SOURCE_STATUS__AVAILABLE = "available"
export const INSTALL_PLAN_SOURCE_STATUS__MISSING = "missing"

export const INSTALL_PLAN_SOURCE_STATUSES = [
  INSTALL_PLAN_SOURCE_STATUS__AVAILABLE,
  INSTALL_PLAN_SOURCE_STATUS__MISSING,
] as const

export const INSTALL_PLAN_DEPENDENCY_KIND__PEER = "peer"
export const INSTALL_PLAN_DEPENDENCY_KIND__RUNTIME = "runtime"
export const INSTALL_PLAN_DEPENDENCY_KIND__DEV = "dev"

export const INSTALL_PLAN_DEPENDENCY_KINDS = [
  INSTALL_PLAN_DEPENDENCY_KIND__PEER,
  INSTALL_PLAN_DEPENDENCY_KIND__RUNTIME,
  INSTALL_PLAN_DEPENDENCY_KIND__DEV,
] as const

export const INSTALL_PLAN_DEPENDENCY_STATUS__SATISFIED = "satisfied"
export const INSTALL_PLAN_DEPENDENCY_STATUS__MISSING = "missing"
export const INSTALL_PLAN_DEPENDENCY_STATUS__INCOMPATIBLE = "incompatible"
export const INSTALL_PLAN_DEPENDENCY_STATUS__UNRESOLVED = "unresolved"

export const INSTALL_PLAN_DEPENDENCY_STATUSES = [
  INSTALL_PLAN_DEPENDENCY_STATUS__SATISFIED,
  INSTALL_PLAN_DEPENDENCY_STATUS__MISSING,
  INSTALL_PLAN_DEPENDENCY_STATUS__INCOMPATIBLE,
  INSTALL_PLAN_DEPENDENCY_STATUS__UNRESOLVED,
] as const

export const REGISTRY_ITEM_TYPE__COMPONENT = "component"
export const REGISTRY_ITEM_TYPE__SUPPORT = "support"
export const REGISTRY_ITEM_TYPE__STYLE = "style"
export const REGISTRY_ITEM_TYPE__THEME = "theme"
export const REGISTRY_ITEM_TYPE__ASSET = "asset"
export const REGISTRY_ITEM_TYPE__TEST = "test"

export const REGISTRY_ITEM_TYPES = [
  REGISTRY_ITEM_TYPE__COMPONENT,
  REGISTRY_ITEM_TYPE__SUPPORT,
  REGISTRY_ITEM_TYPE__STYLE,
  REGISTRY_ITEM_TYPE__THEME,
  REGISTRY_ITEM_TYPE__ASSET,
  REGISTRY_ITEM_TYPE__TEST,
] as const

export const REGISTRY_FILE_ROLE__SOURCE = "source"
export const REGISTRY_FILE_ROLE__STYLE = "style"
export const REGISTRY_FILE_ROLE__TEST = "test"
export const REGISTRY_FILE_ROLE__THEME = "theme"
export const REGISTRY_FILE_ROLE__SUPPORT = "support"
export const REGISTRY_FILE_ROLE__ASSET = "asset"

export const REGISTRY_FILE_ROLES = [
  REGISTRY_FILE_ROLE__SOURCE,
  REGISTRY_FILE_ROLE__STYLE,
  REGISTRY_FILE_ROLE__TEST,
  REGISTRY_FILE_ROLE__THEME,
  REGISTRY_FILE_ROLE__SUPPORT,
  REGISTRY_FILE_ROLE__ASSET,
] as const

export const INSTALL_PLAN_FINDING_SEVERITY__INFO = "info"
export const INSTALL_PLAN_FINDING_SEVERITY__WARNING = "warning"
export const INSTALL_PLAN_FINDING_SEVERITY__ERROR = "error"

export const INSTALL_PLAN_FINDING_SEVERITIES = [
  INSTALL_PLAN_FINDING_SEVERITY__INFO,
  INSTALL_PLAN_FINDING_SEVERITY__WARNING,
  INSTALL_PLAN_FINDING_SEVERITY__ERROR,
] as const

export const INSTALL_PLAN_FINDING__DUPLICATE_ITEM = "duplicate-item"
export const INSTALL_PLAN_FINDING__MISSING_ITEM = "missing-item"
export const INSTALL_PLAN_FINDING__MISSING_DEPENDENCY = "missing-registry-dependency"
export const INSTALL_PLAN_FINDING__CIRCULAR_DEPENDENCY = "circular-registry-dependency"
export const INSTALL_PLAN_FINDING__DUPLICATE_FILE_TARGET = "duplicate-file-target"
export const INSTALL_PLAN_FINDING__TARGET_FILE_EXISTS = "target-file-exists"
export const INSTALL_PLAN_FINDING__SUPPORT_TARGET_REUSED = "support-target-reused"
export const INSTALL_PLAN_FINDING__SOURCE_FILE_MISSING = "source-file-missing"
export const INSTALL_PLAN_FINDING__COMPONENT_PACKET_UNAVAILABLE = "component-packet-unavailable"
export const INSTALL_PLAN_FINDING__CONSUMER_CONFIG_MISSING = "consumer-config-missing"
export const INSTALL_PLAN_FINDING__CONSUMER_CONFIG_INVALID = "consumer-config-invalid"
export const INSTALL_PLAN_FINDING__CONSUMER_LOCKFILE_MISSING = "consumer-lockfile-missing"
export const INSTALL_PLAN_FINDING__CONSUMER_LOCKFILE_INVALID = "consumer-lockfile-invalid"
export const INSTALL_PLAN_FINDING__UNRESOLVED_DEPENDENCY_VERSION = "unresolved-dependency-version"
export const INSTALL_PLAN_FINDING__DEPENDENCY_MISSING = "dependency-missing"
export const INSTALL_PLAN_FINDING__DEPENDENCY_INCOMPATIBLE = "dependency-incompatible"
export const INSTALL_PLAN_FINDING__STRICT_ADD_DEPENDENCY_BLOCKER = "strict-add-dependency-blocker"
export const INSTALL_PLAN_FINDING__STRICT_ADD_DEPENDENCY_EXECUTION_FAILED = "strict-add-dependency-execution-failed"
export const INSTALL_PLAN_FINDING__STRICT_ADD_EXISTING_TARGET_BLOCKER = "strict-add-existing-target-blocker"
export const INSTALL_PLAN_FINDING__STRICT_ADD_PLAN_BLOCKER = "strict-add-plan-blocker"
export const INSTALL_PLAN_FINDING__STRICT_ADD_SOURCE_BLOCKER = "strict-add-source-blocker"
