export default {
  printWidth: 120,
  tabWidth: 2,
  semi: false,
  singleQuote: false,
  trailingComma: "all",
  arrowParens: "always",
  bracketSpacing: true,
  bracketSameLine: false,
  proseWrap: "preserve",
  endOfLine: "lf",
  useTabs: false,
  quoteProps: "as-needed",
  jsxSingleQuote: false,
  htmlWhitespaceSensitivity: "css",
  singleAttributePerLine: false,
  embeddedLanguageFormatting: "auto",
  requirePragma: false,
  insertPragma: false,
};
