export const TYPEAHEAD_SEARCH_STATUS__IDLE = "idle"
export const TYPEAHEAD_SEARCH_STATUS__MINIMUM_QUERY = "minimum-query"
export const TYPEAHEAD_SEARCH_STATUS__LOADING = "loading"
export const TYPEAHEAD_SEARCH_STATUS__ERROR = "error"
export const TYPEAHEAD_SEARCH_STATUS__EMPTY = "empty"
export const TYPEAHEAD_SEARCH_STATUS__RESULTS = "results"

export const AVAILABLE_TYPEAHEAD_SEARCH_STATUSES = [
  TYPEAHEAD_SEARCH_STATUS__IDLE,
  TYPEAHEAD_SEARCH_STATUS__MINIMUM_QUERY,
  TYPEAHEAD_SEARCH_STATUS__LOADING,
  TYPEAHEAD_SEARCH_STATUS__ERROR,
  TYPEAHEAD_SEARCH_STATUS__EMPTY,
  TYPEAHEAD_SEARCH_STATUS__RESULTS,
] as const

export type TTypeaheadSearchStatus = (typeof AVAILABLE_TYPEAHEAD_SEARCH_STATUSES)[number]
