export const CODON_UI_CONFIG_FILE_NAME = "codon-ui.config.json"
export const CODON_UI_LOCK_FILE_NAME = "codon-ui.lock.json"
export const CODON_UI_CONSUMER_PACKAGE_MANIFEST_FILE_NAME = "package.json"
export const CODON_UI_CLI_PACKAGE_NAME = "@codon-ui/cli"
export const CODON_UI_CLI_SHORTCUT_SCRIPT_NAME = "cui"
export const CODON_UI_CLI_SHORTCUT_SCRIPT_COMMAND = "cui"
export const CODON_UI_CLI_SHORTCUT_DEFAULT_DEV_DEPENDENCY_RANGE = "0.2.1"

export const CONSUMER_LAYOUT_MODE__REGISTRY_CONTAINED = "registry-contained"
export const CONSUMER_LAYOUT_MODE__INTEGRATED = "integrated"
export const CONSUMER_LAYOUT_MODE__CUSTOM = "custom"

export const CONSUMER_LAYOUT_MODES = [
  CONSUMER_LAYOUT_MODE__REGISTRY_CONTAINED,
  CONSUMER_LAYOUT_MODE__INTEGRATED,
  CONSUMER_LAYOUT_MODE__CUSTOM,
] as const

export const CONSUMER_TARGET_ROLE__COMPONENTS = "components"
export const CONSUMER_TARGET_ROLE__TOKENS = "tokens"
export const CONSUMER_TARGET_ROLE__UTILS = "utils"
export const CONSUMER_TARGET_ROLE__TYPES = "types"
export const CONSUMER_TARGET_ROLE__THEME = "theme"
export const CONSUMER_TARGET_ROLE__ASSETS = "assets"

export const CONSUMER_TARGET_ROLES = [
  CONSUMER_TARGET_ROLE__COMPONENTS,
  CONSUMER_TARGET_ROLE__TOKENS,
  CONSUMER_TARGET_ROLE__UTILS,
  CONSUMER_TARGET_ROLE__TYPES,
  CONSUMER_TARGET_ROLE__THEME,
  CONSUMER_TARGET_ROLE__ASSETS,
] as const

export const CONSUMER_THEME_TIER__DEFAULT_CONTRACT = "default-contract"
export const CONSUMER_THEME_TIER__PROOF_COMPATIBILITY_BRIDGE = "proof-compatibility-bridge"
export const CONSUMER_THEME_TIER__CONSUMER_OWNED = "consumer-owned"

export const CONSUMER_THEME_TIERS = [
  CONSUMER_THEME_TIER__DEFAULT_CONTRACT,
  CONSUMER_THEME_TIER__PROOF_COMPATIBILITY_BRIDGE,
  CONSUMER_THEME_TIER__CONSUMER_OWNED,
] as const

export const CONSUMER_DEPENDENCY_POLICY__REPORT_ONLY = "report-only"
export const CONSUMER_DEPENDENCY_POLICY__MANUAL = "manual"
export const CONSUMER_DEPENDENCY_POLICY__PROMPT = "prompt"
export const CONSUMER_DEPENDENCY_POLICY__INSTALL = "install"

export const CONSUMER_DEPENDENCY_POLICIES = [
  CONSUMER_DEPENDENCY_POLICY__REPORT_ONLY,
  CONSUMER_DEPENDENCY_POLICY__MANUAL,
  CONSUMER_DEPENDENCY_POLICY__PROMPT,
  CONSUMER_DEPENDENCY_POLICY__INSTALL,
] as const

export const CONSUMER_DEPENDENCY_ACTION__NONE = "none"
export const CONSUMER_DEPENDENCY_ACTION__INSTALLED = "installed"
export const CONSUMER_DEPENDENCY_ACTION__UPDATED = "updated"
export const CONSUMER_DEPENDENCY_ACTION__SKIPPED = "skipped"

export const CONSUMER_DEPENDENCY_ACTIONS = [
  CONSUMER_DEPENDENCY_ACTION__NONE,
  CONSUMER_DEPENDENCY_ACTION__INSTALLED,
  CONSUMER_DEPENDENCY_ACTION__UPDATED,
  CONSUMER_DEPENDENCY_ACTION__SKIPPED,
] as const

export const CONSUMER_PACKAGE_MANAGER__BUN = "bun"
export const CONSUMER_PACKAGE_MANAGER__NPM = "npm"
export const CONSUMER_PACKAGE_MANAGER__PNPM = "pnpm"
export const CONSUMER_PACKAGE_MANAGER__YARN = "yarn"
export const CONSUMER_PACKAGE_MANAGER__UNKNOWN = "unknown"

export const CONSUMER_PACKAGE_MANAGERS = [
  CONSUMER_PACKAGE_MANAGER__BUN,
  CONSUMER_PACKAGE_MANAGER__NPM,
  CONSUMER_PACKAGE_MANAGER__PNPM,
  CONSUMER_PACKAGE_MANAGER__YARN,
  CONSUMER_PACKAGE_MANAGER__UNKNOWN,
] as const

export const CONSUMER_OWNERSHIP_STATE__REGISTRY_OWNED = "registry-owned"
export const CONSUMER_OWNERSHIP_STATE__LOCALLY_MODIFIED = "locally-modified"
export const CONSUMER_OWNERSHIP_STATE__CONSUMER_OWNED_SUPPORT = "consumer-owned-support"
export const CONSUMER_OWNERSHIP_STATE__EJECTED = "ejected"
export const CONSUMER_OWNERSHIP_STATE__UNKNOWN = "unknown"

export const CONSUMER_OWNERSHIP_STATES = [
  CONSUMER_OWNERSHIP_STATE__REGISTRY_OWNED,
  CONSUMER_OWNERSHIP_STATE__LOCALLY_MODIFIED,
  CONSUMER_OWNERSHIP_STATE__CONSUMER_OWNED_SUPPORT,
  CONSUMER_OWNERSHIP_STATE__EJECTED,
  CONSUMER_OWNERSHIP_STATE__UNKNOWN,
] as const

export const CONSUMER_ADVISORY_SEVERITY__INFO = "info"
export const CONSUMER_ADVISORY_SEVERITY__WARNING = "warning"
export const CONSUMER_ADVISORY_SEVERITY__ERROR = "error"

export const CONSUMER_ADVISORY_SEVERITIES = [
  CONSUMER_ADVISORY_SEVERITY__INFO,
  CONSUMER_ADVISORY_SEVERITY__WARNING,
  CONSUMER_ADVISORY_SEVERITY__ERROR,
] as const

export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__NOT_REQUESTED = "not-requested"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__RECOMMENDED = "recommended"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__WOULD_WRITE = "would-write"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__WRITTEN = "written"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__ALREADY_CONFIGURED = "already-configured"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__BLOCKED = "blocked"
export const CONSUMER_INIT_CLI_SHORTCUT_STATUS__MISSING_PACKAGE_JSON = "missing-package-json"

export const CONSUMER_INIT_CLI_SHORTCUT_STATUSES = [
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__NOT_REQUESTED,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__RECOMMENDED,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__WOULD_WRITE,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__WRITTEN,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__ALREADY_CONFIGURED,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__BLOCKED,
  CONSUMER_INIT_CLI_SHORTCUT_STATUS__MISSING_PACKAGE_JSON,
] as const

export const DEFAULT_REGISTRY_CONTAINED_COMPONENTS_PATH = "src/components"
export const DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH = "src/components/_codon-ui-registry"
export const DEFAULT_REGISTRY_CONTAINED_TARGET_PATHS = {
  [CONSUMER_TARGET_ROLE__ASSETS]: `${DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH}/assets`,
  [CONSUMER_TARGET_ROLE__COMPONENTS]: DEFAULT_REGISTRY_CONTAINED_COMPONENTS_PATH,
  [CONSUMER_TARGET_ROLE__THEME]: DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH,
  [CONSUMER_TARGET_ROLE__TOKENS]: `${DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH}/tokens`,
  [CONSUMER_TARGET_ROLE__TYPES]: `${DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH}/types`,
  [CONSUMER_TARGET_ROLE__UTILS]: `${DEFAULT_REGISTRY_CONTAINED_REGISTRY_PATH}/utils`,
} as const
